trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: '$(build.artifactstagingdirectory)'
    FodConnection: 'FOD_Local_Connection'
    ReleaseOptions: '0'
    ReleaseId: 275
    EntitlementSelection: '1'
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '0'
    BuildType: 'none'
    PolicyFailAction: '0'
