# Maven
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.9'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: '$(build.artifactstagingdirectory)'
    FodConnection: 'FOD_Local_Connection'
    ReleaseOptions: '0'
    ReleaseId: 275
    EntitlementSelection: '1'
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '0'
    BuildType: 'mvn'
    PolicyFailAction: '0'
